apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mysql
    namespace: default
    labels:
      app: mysql
  spec:
    selector:
      matchLabels:
        app: mysql
    serviceName: mysql
    replicas: 1
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - name: mysql
          image: mysql:5.7
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          ports:
          - name: mysql
            containerPort: 3306
          volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
          - name: data
            mountPath: /var/lib/mysql
            subPath: mysql
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
        volumes:
        - name: conf
          emptyDir: {}
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 0.5Gi